### ISSUE TITLE
During minikube start there is an Error on Linux, should I worry or not?

### ISSUE THREAD

**Issue by zoneout215** [abelsiqueira/asreview-cloud#3]
After `minikube start` I experience this erorr, but everything works fine after this. 

m/rabbitmq/cluster-operator/releases/latest/download/cluster-operator.yml"😄  minikube v1.30.1 on Ubuntu 20.04 (amd64)
✨  Automatically selected the docker driver. Other choices: ssh, none
📌  Using Docker driver with root privileges
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔥  Creating docker container (CPUs=2, Memory=16000MB) ...| E0528 08:15:17.810888 3192134 network_create.go:102] failed to find free subnet for docker network minikube after 20 attempts: no free private network subnets found with given parameters (start: "192.168.49.0", step: 9, tries: 20)

❗  Unable to create dedicated network, this might result in cluster IP change after restart: un-retryable: no free private network subnets found with given parameters (start: "192.168.49.0", step: 9, tries: 20)

🐳  Preparing Kubernetes v1.26.3 on Docker 23.0.2 ...| E0528 08:15:28.094721 3192134 start.go:131] Unable to get host IP: network inspect: docker network inspect minikube --format "{"Name": "{{.Name}}","Driver": "{{.Driver}}","Subnet": "{{range .IPAM.Config}}{{.Subnet}}{{end}}","Gateway": "{{range .IPAM.Config}}{{.Gateway}}{{end}}","MTU": {{if (index .Options "com.docker.network.driver.mtu")}}{{(index .Options "com.docker.network.driver.mtu")}}{{else}}0{{end}}, "ContainerIPs": [{{range $k,$v := .Containers }}"{{$v.IPv4Address}}",{{end}}]}": exit status 1
stdout:

stderr:
Error response from daemon: network minikube not found

**Comment by abelsiqueira** [comment]
As far as I understood, this error happens because of the way that SURF works. It does not allow network access without extra plugins. It does not look like we need it, because everything else worked.
